name: Create Release PR

on:
  push:
    branches: [master]
    paths:
      - '.changeset/**'

jobs:
  version:
    if: |
      github.event.head_commit.message != 'Version Packages' &&
      github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - uses: changesets/action@v1
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
