name: Create Release PR

on:
  push:
    branches: [master]

jobs:
  version:
    if: |
      github.ref == 'refs/heads/master' &&
      github.event.head_commit.message != 'Version Packages' &&
      github.event.head_commit.message != 'Release'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: 20

      - run: npm ci

      - uses: changesets/action@v1
        with:
          publish: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Push version tags
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "justabot@bot.justabot"
          git push --follow-tags
